services:
  redis:
    image: redis/redis-stack:7.2.0-v10
    expose:
      - 6379
      - 8001
    command: [ "/entrypoint.sh", "./redis-stack.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data