name: Deploy GCP VM

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy-vm:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # JSON key from GitHub Secrets
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run Deployment Script
        run: |
          # Make the script executable
          chmod +x deploy-to-vm.sh
          # Run the script (replace with your script's path)
          ./deploy-to-vm.sh
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          INSTANCE_NAME: crowdfund-backend-vm
          ZONE: us-central1-a
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: crowdfund
          MACHINE_TYPE: f1-micro # Adjust as needed
          IMAGE_PROJECT: debian-cloud # Adjust as needed
          IMAGE_FAMILY: debian-11 # Adjust as needed