name: Run Tests on Push

on:
  push:
    branches: [ "main" ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ "main" ]  # Also run on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Adjust based on test duration
    services:
          postgres:
            image: postgres:16
            env:
              POSTGRES_USER: test
              POSTGRES_PASSWORD: test
              POSTGRES_DB: test
            ports: ["5432:5432"]
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      
      - name: Run Tests with DB
        env:
          DATABASE_URL: "postgres://test:test@localhost:5432/test"
        run: |
          cd backend
          go test -v ./...